: SQUARE ( n -- )
  DUP 0 DO
    DUP FORWARD
    90 RIGHT
  LOOP DROP ;

: PATTERN ( depth size -- )
  DUP 0= IF DROP DROP EXIT THEN
  DUP SQUARE
  DUP 2 / SWAP 1- RECURSE
  72 RIGHT
  DUP 2 / SWAP 1- RECURSE
  72 LEFT ;

: MAIN
  4 100 PATTERN ;

MAIN